Add files via upload
Amsterdam/ee-react-map-demos pull request #50
Opened 2024-07-17 13:23 UTC by amnad001

Added CODEOWNERS

2024-07-18 07:24 UTC, SireeKoolenWijkstra requested changes
Please reference in your PR title wether it is a fix/ chore/ feature etc (see https://developers.amsterdam/docs/general/using-git) and the Jira number. Please use this format for all future PR's. 

It is not a .txt

2024-07-18 09:01 UTC, thomasm0 commented
Just for future reference, please review:
1. Branch name
2. Add reviewers
3. Filename should be `CODEOWNERS`, not `CODEOWNERS.txt`

2024-07-19 15:42 UTC, thomasm0 requested changes
Just for future reference, please review:
1. Branch name - `CODEOWNERS` --> `chore/com-176-codeowners` (something like `[type]/[ticket-number]-[feature-name]`)
2. Add reviewers
3. Filename should be `CODEOWNERS`, not `CODEOWNERS.txt` + in the file make `Engineering-Enablement` lowercase

2024-07-23 09:20 UTC, thomasm0 approved these changes

2024-07-23 09:21 UTC, merged